### ISSUE TITLE
More lessons visible on built page

### ISSUE THREAD

**Issue by mjones01** [NEONInc/NEON-Lesson-Building-Data-Skills#7]
Fix the template to be able to view more (20+) posts on the github.io page.  
http://neoninc.github.io/NEON-DataSkills-Lesson-Development/   

Currently can't see all the pages.

**Comment by lwasser** [comment]
ok we can fix this but this means that the home page in this repo will be DIFFERENT than the home page on the actual site. IS that ok? I suppose it is for these dev repos.

**Comment by mjones01** [comment]
I would say for NEON-Lessons-Building repo (and any other building repos) that having all the lessons visible is important; not, however, for NEON-Data-Skills-Development.
